language: cpp
sudo: required
dist: bionic
compiler:
- clang
os:
- linux
script:
- sh build.sh
before_deploy:
- sh ./before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: xuqgLf7bLAI7iplVitWA4zRNgae53ER4abiKyc05347q+qxxqS03tX5+qMPf0a/XJHvO/2R272GQrlDEPMu3WgJ0ZYyy9nZ7Q+YO7dbZVwdQrADJJDGTw2Cwu+FhjKE/B30PN8piTlkLzdwOoPS3yJCI/NeGeqttuQefVOco+s2TPyKrWNOGCAJdEa9unNONcBcwLjUDQuq4IeTMga0Sy9nGSHRIKb0HGM1TjnoTYwvUugiQa5y9ZuuHJspceiNQ2evzbOdSiAH5N8lYK8s9w/pxBCiFXoe3jBujOi5o6f1k8Qh92XKeCp8PDSTUxdEpNQm0+9J2F5wzVK+qPPNo+8DIRbp9eN35c89j2pBA+qKiXrWD0q1B/qocLPKklRIG3drbd7QE88IK2gIy2/+klqKLMqPYGK8MJIZaAKcpO5jjiV71c9dCqT7tFEUBHM8KXbabXxSwOtt3DCb5O1rERszhp3m+WEwZEsz6qjLs35ML/HBQjZr5/nnFPTwdPJawlI5ZNH2CjVwxH0y3GQv/Ixj65wrxuSnnwUbDb2uZGE49DzVBtj5MiMQS8WgLugjVYjlZwXyZtJy7Jjqd8B0rMPm3J1MSvPtRDXzj+jToSasRSZZrIE93xj6FNrrzXOJmdyhPeIAimGBPBBqMUVeP2KNtaiqBsDuZsdg9DW/ZdRM=
  file: toolchain.tar.gz
  on:
    repo: orbisdev/orbis-sysroot
  skip_cleanup: 'true'
branches:
  except:
  - "/^*-v[0-9]/"
