language: cpp
sudo: required
dist: bionic
compiler:
- clang
os:
- linux
before_install:
  - sudo apt-get update
  - sudo apt-get -y install ninja-build
script:
- sh build.sh
deploy:
  provider: releases
  api_key:
    secure: U8x4GoBxJ2q/tilQKw7WX0U2QYI3ckg97ZPTrFcWG+Lw6oYLszilgZNlyKZIHtdiD6aZp46wHK/MkRlKpeKi5NFTy/65ksiVuBkuxKdpbKHxUxvYmcHjZY4nRGB0kcIZTZDFrguw8BkwXFyKVg7MyAoeS3NK4bOlgfr96w0CPhPZ9po+wTzKgZYehTK6T8KLTRXisiMueXFJxW+ubO78weI/YGOgJiu9Bv7FIvcNDg1Z9vLLh7m+DOjXhK8O/oYoELFTRH+Wq/PIH3Lb5CssBvMrQ3hcbaPO+H3G+NpS1DjhlZPSzmU7A0AE0Iw+f6VNH0UWtywjz6av/lBte9CodIGDoQfQ3zP7yleG9Cl/JSwLSUC//AW22H3yIXkPKwPk6blQebfYeikWyeX1V30ySe6jFylGTPwftU7Vy40VHlAZwRmiZ6ag2cr80OrNc0biUvJJ1EvJW+q/TDWM0cfTy75ykms51iKOD3Z4oC/SX9KjKqU/Nb1fJhm+yo0iRMCY+lNXbqFQX8OPqthttcievlKvxoSpEExi5Ro4+0ANRhRai1Fmvj/0icMH01vvupVv4ZPGidmRk6v7HerryE1UoNOXYGqj+ikov4Qlbu0QUdWJWQ/+BMJ5UppGJgqOTQYIHKR4sru4Ug7w7aGnYPpzJRhqXISpjFG+9BRSo0sFLSw=
  file: toolchain.tar.gz
  name: "$TRAVIS_REPO_SLUG-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER-$(git rev-parse --short HEAD)"
  body: "Release Autogenerated by TravisCI for the branch $TRAVIS_BRANCH in the commit $TRAVIS_COMMIT"
  on:
    repo: $TRAVIS_REPO_SLUG
  skip_cleanup: 'true'
